### ISSUE TITLE
Used with Advanced Mask, it will appear as a vignette.

### ISSUE THREAD

**Issue by ZRdRy** [exeldro/obs-3d-effect#14]
GIF: https://imgur.com/a/oAk3LIs

After using 3D Effect and adding an Advanced Mask on top of 3D Effect, the vignette will appear, but if you add another filter underneath it, such as Shadow, Glow, Chroma Key, etc., the vignette will disappear and become normal. I don't have this problem after testing streamFX 3D effects

**Comment by exeldro** [comment]
Made a fix, can you test the new build?
https://github.com/exeldro/obs-3d-effect/actions/runs/11854615092

**Comment by ZRdRy** [comment]
> Made a fix, can you test the new build? https://github.com/exeldro/obs-3d-effect/actions/runs/11854615092

Thanks, I tested it and it's working fine

**Comment by mtackes** [comment]
I'm having the same issue now. Tested recent versions, and the regression happened between 0.1.2 and 0.1.3.
