### ISSUE TITLE
Add de-DE translation

### ISSUE THREAD

**Issue by ViP3R76** [exeldro/obs-3d-effect#3]
Hi, could not open a PR. I am not so familiar with GitHub. Simple, but maybe just a little cent to make the world better. :-)

locale/de_DE.ini:
```
3DEffect="3D Effect"
Description="3D Effect Filter"
FieldOfView="Sichtfeld"
Rotation="Rotation"
RotX="Rotation X"
RotY="Rotation Y"
RotZ="Rotation Z"
Position="Position"
PosX="Position X"
PosY="Position Y"
PosZ="Position Z"
Scale="Skalierung"
ScaleX="Skalierung X"
ScaleY="Skalierung Y"
```

**Comment by exeldro** [comment]
I added it for you: https://github.com/exeldro/obs-3d-effect/commit/2a029bc677828ce6f88a1ace06d25b30d62bc0f5
It should be in the next release.
