### ISSUE TITLE
Works with OBS 29.0.2?

### ISSUE THREAD

**Issue by dstanley4** [exeldro/obs-3d-effect#4]
I'm using OBS 29.0.2 and I installed the x86 macOS version obtained from the OBS website. After install I did not see the 3D effects filter show up in the list of filters. Is this software compatible with OBS 29?

**Comment by exeldro** [comment]
Yes it should work fine. Is the plugin showing in the obs log file?

**Comment by dstanley4** [comment]
Not showing under Loaded Modules:

**Comment by exeldro** [comment]
If it also does not show a failed to load error there is something wrong with the installation. As I don't have a mac and no mac experience I can't help you with that. Maybe try installing the universal version.

**Comment by dstanley4** [comment]
Ok - will try that.  Thanks for your help. Much appreciated!

On Apr 15, 2023, at 3:46 PM, Exeldro ***@***.***> wrote:


CAUTION: This email originated from outside of the University of Guelph. Do not click links or open attachments unless you recognize the sender and know the content is safe. If in doubt, forward suspicious emails to ***@***.***




If it also does not show a failed to load error there is something wrong with the installation. As I don't have a mac and no mac experience I can't help you with that. Maybe try installing the universal version.

**Comment by dstanley4** [comment]
Ok - I've managed to install the software and it's great. Not sure why it's working though. Multiple/multiple install attempts (with restarts in between). Finally worked today for some reason on the third try. Maybe something sometimes causes problems for the Mac installer. Thanks again for your help!
