### ISSUE TITLE
Mac M1 Apple silicon arm64 - needed

### ISSUE THREAD

**Issue by nunowonder** [exeldro/obs-3d-effect#5]
Hello, I need this version! It it feasible and will be fast? Thank you!

**Comment by exeldro** [comment]
What is wrong with the available arm 64 version?

**Comment by nunowonder** [comment]
@exeldro thsnk you so much for your response! Well, because there is no arm64 version, if I install it, the plug-in simply won’t open in OBS … or… maybe I can’t find it? 

P.s. thank you so much for your brilliant work, I use your work a lot!!!

**Comment by exeldro** [comment]
Does the plugin show in your OBS log file? What directory did you install the plugin in?

**Comment by nunowonder** [comment]
Hello Exeldro, 
Well, it was installed automatically on Library/Application Support/Obs-studio/plugins.
Now I moved to users/(myname)/Library/Application Support/Obs-studio/plugins and it's working! Thanx
But anyway maybe the installer is not correct, it souldnt be on that folder right?

Edit2 - never mind! It's working!
