### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by YorVeX** [exeldro/obs-3d-effect#8]
**Setup:** obs-3d-effect 0.0.2 with OBS 29.1.3 on Windows 10 64 bit

**Repro:**
- Run OBS and exit it again with obs-3d-effect installed but no 3D effect filter added anywhere, check the OBS log -> no memory leaks
- Run OBS again, add a 3D effect filter to a sync source (e.g. color source or text source), exit OBS, check the OBS log -> 2 memory leaks per added filter will be shown

It only happens for sync sources, when adding the filter to an async source (e.g. media source) no memory leaks are caused.

**Comment by exeldro** [comment]
I got 4 memory leaks while replicating it. They should be fixed now in master.

**Comment by YorVeX** [comment]
No longer seeing memory leaks with latest master build, thanks!
